### ISSUE TITLE
Missing component?

### ISSUE THREAD

**Issue by grafsoft** [Asedem/OllamaJavaAPI#1]
I get Failed to execute goal on project Ollamax: Could not resolve dependencies for project com.grafsoft:Ollamax:jar:1.0-SNAPSHOT: The following artifacts could not be resolved: de.asedem:ConnectionAPI:jar:1.0-SNAPSHOT (absent): Could not find artifact de.asedem:ConnectionAPI:jar:1.0-SNAPSHOT -> [Help 1]

What am I doing wrong? I do not find any reference to de.asedem:ConnectionAPI

Best

Peter

**Comment by Asedem** [comment]
The bug should be fixed in the latest version. It was caused by the local import of a library.
